#!/bin/bash
set -euo pipefail

# build-dmg.sh — Build local unsigned Release App and package into DMG.
#
# Usage: ./scripts/build-dmg.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

VERSION=$(grep "MARKETING_VERSION:" project.yml | sed 's/.*MARKETING_VERSION: //' | tr -d ' ')
DMG_NAME="Ora-Browser-${VERSION}-Unsigned.dmg"

echo "========================================"
echo "Building Ora Browser v${VERSION} (Release)..."
echo "========================================"

# Clean up previous builds
rm -rf build/
mkdir -p build

echo "Generating Xcode project..."
xcodegen

echo "Building app bundle (unsigned)..."
if command -v xcbeautify >/dev/null 2>&1; then
    xcodebuild build \
        -scheme ora \
        -configuration Release \
        -destination "platform=macOS" \
        -derivedDataPath build/DerivedData \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        2>&1 | xcbeautify
else
    xcodebuild build \
        -scheme ora \
        -configuration Release \
        -destination "platform=macOS" \
        -derivedDataPath build/DerivedData \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO
fi

APP_PATH="build/DerivedData/Build/Products/Release/Capy Browser.app"
if [[ -d "$APP_PATH" ]]; then
    echo "Copying built app..."
    cp -R "$APP_PATH" "build/Ora.app"
else
    echo "error: App build failed, bundle not found at $APP_PATH"
    exit 1
fi

echo "========================================"
echo "Packaging into DMG..."
echo "========================================"

if command -v create-dmg >/dev/null 2>&1; then
    create-dmg \
        --app-drop-link 600 185 \
        --window-size 800 400 \
        --volname "Ora Browser" \
        --skip-jenkins \
        "build/${DMG_NAME}" \
        "build/Ora.app" 2>/dev/null || true

    # Handle temp name if generated by create-dmg
    TEMP_DMG=$(ls build/rw.*.dmg 2>/dev/null | head -1 || true)
    [[ -n "$TEMP_DMG" ]] && mv "$TEMP_DMG" "build/${DMG_NAME}"

    if [[ -f "build/${DMG_NAME}" ]]; then
        echo ""
        echo "========================================"
        echo "Build & packaging succeeded!"
        echo "DMG: build/${DMG_NAME}"
        echo "========================================"
    else
        echo "error: DMG creation failed."
        exit 1
    fi
else
    echo "warning: create-dmg is not installed. You can install it using: brew install create-dmg"
    echo "The compiled app is available at: build/Ora.app"
fi
